version: "3.3"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
        restart: unless-stopped
        links:
            - mongodb

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
        restart: unless-stopped
        stdin_open: true
        environment:
            CHOKIDAR_USEPOLLING: "true"

    mongodb:
        build: ./mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mongo/data:/data/db # store MongoDB data in host

    nginx:
        image: nginx
        restart: unless-stopped
        ports: 
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


            